name: CI Edge (TypeScript)
on:
  push: { branches: [ main, fix/**, feature/** ] }
  pull_request:
concurrency: { group: ci-edge-${{ github.ref }}, cancel-in-progress: true }
jobs:
  test-edge:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: . } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - name: Print scripts
        run: node -e "console.log(require('./package.json').scripts)"
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Start app (project server)
        run: |
          NODE_ENV=production npm run start & echo $! > server.pid
          echo "Started with PID=$(cat server.pid)"
      - name: Wait for /health
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:5000/health > /dev/null; then
              echo "Preview ready"; exit 0
            fi
            echo "waiting ($i/60)"; sleep 2
          done
          echo "Preview not ready"; exit 1
      - name: Smoke tests (optional)
        env: { SMOKE_URL: http://localhost:5000 }
        run: |
          if npm run | grep -q "test:smoke"; then
            npm run test:smoke
          else
            echo "No test:smoke; basic probe…"
            curl -fsS $SMOKE_URL/health
            curl -fsS $SMOKE_URL/ | head -n 1
          fi
      - name: Stop app
        if: always()
        run: |
          [ -f server.pid ] && kill $(cat server.pid) || true
      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: edge-logs
          path: |
            **/npm-debug.log
            server.pid
          if-no-files-found: ignore