name: CI Edge (TypeScript)

on:
  push:
    branches: [ main, fix/**, feature/** ]
  pull_request:

concurrency:
  group: ci-edge-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Start preview server
        run: node scripts/mini-server.js &
      - name: Wait for /health
        run: |
          for i in {1..30}; do
            if curl -fsS http://localhost:5000/health > /dev/null; then
              echo "Preview ready"; exit 0
            fi
            echo "waiting ($i/30)"; sleep 2
          done
          echo "Preview not ready"; exit 1
      - name: Smoke tests
        env:
          SMOKE_URL: http://localhost:5000
        run: |
          if npm run | grep -q "test:smoke"; then
            npm run test:smoke
          else
            echo "No test:smoke script found; basic check:"
            curl -f $SMOKE_URL/
          fi
      - name: Upload preview logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: edge-smoke-logs
          path: |
            **/npm-debug.log
            **/logs/**/*
          if-no-files-found: ignore